# permissions for end users to edit operatorinspectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorinspector-editor-role
rules:
- apiGroups:
  - inspector.operator-inspector.com
  resources:
  - operatorinspectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inspector.operator-inspector.com
  resources:
  - operatorinspectors/status
  verbs:
  - get
